name: 'Deploy'

on:
  push:
    branches:
      - main
      - staging
      - testing
      - develop

jobs:
  deploy:
    name: 'Deploy'

    runs-on: ubuntu-latest

    steps:
      - name: 'Setup PHP'
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - uses: actions/checkout@v2
      - name: 'Install Composer Dependencies'
        run: composer install -q --no-dev --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: 'Install Node Dependencies'
        run: npm ci
      - name: 'Link Storage'
        run: php artisan storage:link
      - name: 'Build Webpack'
        run: npm run production
      - name: 'Deploy Info'
        id: deploy_info
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: 'Deploy using FTP'
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: httpdocs/${{ steps.deploy_info.outputs.branch }}/
          exclude: .git*
            - **.git*
            - .git*/**
            -  **/.git*/**
            - node_modules/**
            - node_modules/**/*
            - .env*